FitnessTracker/Controllers/ExerciseController.cs
using FitnessTracker.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FitnessTracker.Data;
using FitnessTracker.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FitnessTracker.Controllers
{
    public class ExerciseController : Controller
    {
        private readonly FitnessTrackerDBContext _db;
        public ExerciseController(FitnessTrackerDBContext db)
        {
            _db = db;
        }
       
        public IActionResult CreateExercise()
        {
            var dropdownData = new BodypartCategoryViewModel();
            dropdownData.BodyParts = _db.BodyParts.ToList();
            dropdownData.Category = _db.Categories.ToList();
            //var bodyparts = _db.BodyParts.ToList();
            //var categories = _db.Categories.ToList();
            //ViewBag.BodyParts = bodyparts;
            //ViewBag.Categories = categories;         
            return View(dropdownData);
        }
              
        public IActionResult CreateExerciseAction(ExerciseViewModel exerciseInput)
        {
            User user = _db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            if (user.Id == null)
            {
                throw new Exception("No authenticated user could be found!");
            }
            Excercise newExercise = new Excercise()
            {
                Name = exerciseInput.Name,
                BodypartId = exerciseInput.BodyPartId,
                CategoryId = exerciseInput.CategoryId,
                UserId = user.Id
            };
            _db.Exercises.Add(newExercise);
            _db.SaveChanges();            
            return RedirectToAction("RenderMain", "Dashboard");
        }
    }
}

FitnessTracker/Controllers/FoodController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FitnessTracker.Data;
using FitnessTracker.Migrations;
using FitnessTracker.Models;
using FitnessTracker.ViewModels;

namespace FitnessTracker.Controllers
{
    public class FoodController : Controller
    {
        protected FitnessTrackerDBContext _db;
        public FoodController(FitnessTrackerDBContext context)
        {
            _db = context;
        }
        public IActionResult FoodHistory()
        {
            var user = _db.Users.FirstOrDefault(u => User.Identity.Name == u.UserName);
            FoodHistoryViewModel foodData = new FoodHistoryViewModel()
            {
                foods = GetAllUserFoods(user.Id)
            };
            return View(foodData);
        }

        public IActionResult AddFood()
        {
            CreateFoodViewModel inputFoods = new CreateFoodViewModel();
            List<Food> allFoods = _db.Foods.OrderBy(f => f).ToList();
            inputFoods.allFoods = allFoods;
            inputFoods.uniqueFoods = allFoods.Select(f => f.Name).Distinct().OrderBy(f => f).ToList();
            return View("FoodCreate", inputFoods);
        }

        public IActionResult AddFoodAction(Food food)
        {
            food.UserId = _db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name).Id;
            food.DateAdded = DateTime.Now;
            _db.Foods.Add(food);
            _db.SaveChanges();
            return RedirectToAction("RenderMain", "Dashboard");
        }

        public IActionResult AddPreAddedFood(PreAddedFoodViewModel inputData)
        {
            string userId = _db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name).Id;
            if (userId == null)
            {
                throw new Exception("No Authenticated user could be found!");
            }
            int count = inputData.Number;
            string foodName = inputData.Name;
            Food foodInfo = _db.Foods.FirstOrDefault(f => f.Name == foodName);
            if (foodInfo == null)
            {
                throw new Exception("Food could not be found!");
            }
            if (count <= 0)
            {
                throw new Exception("Count is below or equal to zero!");
            }

            if (count > 15)
            {
                throw new Exception("Count number too big!");
            }
            for (int i = 1; i <= count; i++)
            {
                Food foodEntity = new Food()
                {
                    Calories = foodInfo.Calories,
                    Carbohydrates = foodInfo.Carbohydrates,
                    DateAdded = DateTime.Now,
                    Fat = foodInfo.Fat,
                    Name = foodInfo.Name,
                    Protein = foodInfo.Protein,
                    UserId = userId
                };
                _db.Foods.Add(foodEntity);
            }
            _db.SaveChanges();
            return RedirectToAction("RenderMain", "Dashboard");
        }

        public List<FoodDataViewModel> GetAllUserFoods(string userId)
        {
            List<Food> userFoods = _db.Foods.Where(f => f.UserId == userId).ToList();
            userFoods = userFoods.OrderByDescending(f => f.DateAdded).ToList();
            var foodData = new List<FoodDataViewModel>();
            foreach (var userFood in userFoods)
            {
                foodData.Add(new FoodDataViewModel()
                {
                    Name = userFood.Name,
                    DateAdded = userFood.DateAdded,
                    Calories = userFood.Calories,
                    Carbohydrates = userFood.Carbohydrates,
                    Fat = userFood.Fat,
                    Id = userFood.Id,
                    Protein = userFood.Protein,
                    User = userFood.User,
                    UserId = userFood.UserId
                });
            }
            return foodData;
        }
    }
}

FitnessTracker/Controllers/WorkoutController.cs
using FitnessTracker.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FitnessTracker.Data;
using FitnessTracker.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace FitnessTracker.Controllers
{
    public class WorkoutController : Controller
    {
        private readonly FitnessTrackerDBContext _db;
        public WorkoutController(FitnessTrackerDBContext db)
        {
            _db = db;
        }
        [HttpGet]
        public IActionResult WorkoutDetails()
        {
            string name = Request.Path.Value.Split('/').LastOrDefault();
            var targetWorkout = _db.Workouts
                .Include(w => w.Exercises)
                .ThenInclude(e => e.Bodypart)
                .Include(w => w.Exercises)
                .ThenInclude(e => e.Category).FirstOrDefault(w => w.Name == name);
            
            WorkoutDetailsViewModel workout = new WorkoutDetailsViewModel()
            {
                Exercises = targetWorkout.Exercises.ToList(),
                Name = targetWorkout.Name
            };
            //{
            //    Name = w.Name,
            //    Exercises = w.Exercises.ToList()
            //}).FirstOrDefault(w => w.Name == name);


            return View("WorkoutDetails", workout);
        }

        public IActionResult CreateWorkout()
        {
            ExerciseWorkoutDropDViewModel exerciseData = new ExerciseWorkoutDropDViewModel();
            exerciseData.uniqueExercises = _db.Exercises.Select(e => e.Name).Distinct().ToList();
            return View("CreateWorkout", exerciseData);
        }

        public IActionResult CreateWorkoutAction(WorkoutDataViewModel inputWorkoutData)
        {
            var user = _db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            Workout workoutAdd = new Workout()
            {
                Name = inputWorkoutData.Name,
                UserId = user.Id,
            };
            var exerciseList = new List<Excercise>();
            foreach (var exercise in inputWorkoutData.ExerciseNames)
            {
                var exerciseFind = _db.Exercises.FirstOrDefault(e => e.Name == exercise);
                if (exerciseFind == null)
                { throw new Exception("No exercise with such name could be found!"); }
                exerciseList.Add(exerciseFind);
            }

            workoutAdd.Exercises = exerciseList;
            _db.Workouts.Add(workoutAdd);
            _db.SaveChanges();
            return RedirectToAction("RenderMain", "Dashboard");
        }
    }
}

FitnessTracker/Views/Shared/DashboardSidebarPartial.cshtml
<div class="activitywhitecontainer"></div>
<div class="col-2 mycols">
    <div style="margin-left:10px; margin-top:10px;">
        <h3 class="mb-5">Add activity</h3>
        <a asp-controller="Food" asp-action="AddFood" style="text-decoration: none">
            <div class="button regbtn" id="button-2">
                <div id="slide"></div>
                <div class="innerText"><i class="fas fa-utensils"></i> Food</div>
            </div>
        </a>
        <a asp-controller="Exercise" asp-action="CreateExercise" style="text-decoration: none">
            <div class="button regbtn" id="button-2">
                <div id="slide"></div>
                <div class="innerText"><i class="fas fa-dumbbell"></i> Exercise</div>
            </div>
        </a>
        <a asp-controller="Workout" asp-action="CreateWorkout">
            <div class="button regbtn" id="button-2">
                <div id="slide"></div>
                <div class="innerText"><i class="fas fa-plus"> Workout</i></div>
            </div>
        </a>
    </div>
</div>

FitnessTracker/Views/Shared/FooterPartial.cshtml
<footer class="border-top footer text-muted mainFooter">
    <div class="container">
        &copy; 2021 - FitnessTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

FitnessTracker/Views/Shared/NavbarPartial.cshtml
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 navbarHeight">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FitnessTracker</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

FitnessTracker/Views/Shared/WorkoutDashboard.cshtml
<div class="workoutlistwhitecontainer"></div>
<div class="limiter">
    <div style="margin-left:15px;margin-top:5px">
        <div class="wrap-table100">
            <div class="table100">
                <script type="text/javascript">

                </script>
                <table class="tableWorkouts">
                    <thead>
                        <tr class="table100-head">
                            <th style="width: 60%">Name</th>
                            <th style="width: 40%">Count of exercises</th>
                        </tr>
                    </thead>
                    @foreach (var workout in Model.userWorkouts)
                    {
                        <tr onclick="RedirectWorkoutDetails(event)" class="backgroundColorWorkout">
                            <td style="width: 60%">@workout.Name</td>
                            <td style="width: 40%;">@workout.ExerciseCount</td>
                        </tr>

                    }
                </table>
            </div>
        </div>
    </div>
</div>

FitnessTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FitnessTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <partial name="NavbarPartial" />
    </header>
    <div class="dashboard h-100 pb-0">
        <main id="main" role="main" class="mt-5 h-100">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/bbf4fa143d.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>